# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches: [ main ]
  # Opcional: despliegue manual desde GitHub
  workflow_dispatch:

jobs:
  test:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Si tienes dependencias de desarrollo separadas:
          # pip install -r requirements-dev.txt

      # Cuando tengas pruebas, descomenta esto:
      # - name: Run tests
      #   run: pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: hydrous-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Construir la imagen Docker
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          # Subir la imagen a ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy to AWS
        run: |
          echo "🚀 Iniciando despliegue a producción..."
          ./deploy-with-rollback.sh
          echo "✅ Despliegue completado"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Despliegue exitoso a producción"
          else
            echo "❌ Error en el despliegue a producción"
          fi
      
    